# Config file for [REUSE](https://reuse.software/) tool.
#
# SPDX-FileCopyrightText: 2024 Shota FUJI <pockawoooh@gmail.com>
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
	"tests/**/*",
]
SPDX-FileCopyrightText = "2024 Shota FUJI <pockawoooh@gmail.com>"
SPDX-License-Identifier = "Apache-2.0"
