// Test suites for building third-party packages.
//
// SPDX-FileCopyrightText: 2024 Shota FUJI <pockawoooh@gmail.com>
// SPDX-License-Identifier: Apache-2.0

import { rollup } from "rollup";
import { describe, expect, it } from "vitest";

import { gleam } from "../../src/plugin";

const CIRCULAR_DEPS_FILES_PATTERN =
	/\/build\/dev\/javascript\/(gleam_stdlib|gleam_json|lustre)\//;

describe("Third party packages", () => {
	it("Should include third party packages in the bundle", async ({ onTestFinished }) => {
		const build = await rollup({
			input: new URL("./src/main.js", import.meta.url).pathname,
			onwarn(warning, defaultHandler) {
				// JS files generated by Gleam frequently have circular dependencies.
				// However, that warning is not related to this test because those are
				// upstream problem, not this plugin's one.
				if (
					warning.code === "CIRCULAR_DEPENDENCY" &&
					warning.ids?.every((id) => CIRCULAR_DEPS_FILES_PATTERN.test(id))
				) {
					return;
				}

				return defaultHandler(warning);
			},
			plugins: [
				gleam({
					gleamToml: new URL("./gleam.toml", import.meta.url),
				}),
			],
		});

		onTestFinished(() => build.close());

		const { output } = await build.generate({});

		expect(output).toHaveLength(1);
		expect(
			output[0].moduleIds.some((id) => id.endsWith("/dev/javascript/lustre/lustre.mjs")),
		).toBe(true);
	});
});
